I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 653, in script
    hednra "Ignorance is bliss. Kita lewati saja ini dengan rapi ya?"
Exception: Sayer 'hednra' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 653, in script
    hednra "Ignorance is bliss. Kita lewati saja ini dengan rapi ya?"
  File "C:\Users\ASUS\Downloads\Programs\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\ASUS\Downloads\Programs\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\ASUS\Downloads\Programs\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'hednra' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
KWN 1.0
Sun Nov 24 13:52:32 2024
